### ISSUE TITLE
Where to get the values/version.xml file? :)

### ISSUE THREAD

**Issue by ProgrammingLife** [dandar3/android-google-play-services-ads#2]
I need values/version.xml file (which contains the "google_play_services_version" string). Where do I get that file? :)

**Comment by dandar3** [comment]
Project's README.md lists a number of projects this one depends on and you need to take all of them. Specifically `google_play_services_version` is in `res\values.xml` in `google-play-services-basement`.

Check out the videos at the end of the link below, they will show you an easier way of taking down an entire set. https://github.com/dandar3/android-google-play-services-README
