### ISSUE TITLE
Create latest google ads library version 18.1.1

### ISSUE THREAD

**Issue by vijaybhairavjibhaiaslaliya** [dandar3/android-google-play-services-ads#5]
hello,
can you please create your google play service ads library 18.1.1..??
 your older version is still 15.0.0.. 
Please update this version and create latest ads library.
Thank you.

**Comment by dandar3** [comment]
Hi @vijaybhairavjibhaiaslaliya, will do!

**Comment by vijaybhairavjibhaiaslaliya** [comment]
thank you so much for your 24*7 support

**Comment by strength0179** [comment]
Is that why I keep failing on get ad content?

Thx.

**Comment by dandragut** [comment]
@strength0179 
Please either send me an email with more details (exceptions etc) or create a separate issue so we can follow it through.

**Comment by strength0179** [comment]
Let me update my library first. Thx again.
